create table userRole (id int8 generated by default as identity, name varchar(255), primary key (id))
create table user (id int8 generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id))
create table users_roles (user_id int8 not null, role_id int8 not null)
alter table if exists user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email)
alter table if exists users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references userRole
alter table if exists users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user
